spring:
  application:
    name: appointment-service  # matches config file name
  config:
    import: "configserver:http://localhost:8888"
    fail-fast: true
    retry:
      initial-interval: 1000
      max-attempts: 6